// Generated by CoffeeScript 1.12.6
(function() {
  this.AjaxUtils = (function() {
    function AjaxUtils() {}

    AjaxUtils.sendAjax = function(method, url, callbackContext, callbackSuccess, callbackError, data, onTheFlyData) {
      if ((data == null) || (data === void 0)) {
        data = "";
      }
      return $.ajax({
        url: url,
        type: method,
        crossDomain: true,
        data: data,
        success: function(response) {
          return callbackSuccess.call(callbackContext, response, onTheFlyData);
        },
        error: function(xhr, status) {
          return callbackError.call(callbackContext, xhr, status);
        }
      });
    };

    return AjaxUtils;

  })();

}).call(this);
