// Generated by CoffeeScript 1.12.6
(function() {
  this.AppData = (function() {
    var DEBUG_MODE, FILTERED_ARTISTS_WRITER_URL, FILTER_ARTISTS, GENRES, LAST_ARTIST, LAST_GENRE, LOGGING_ON, LYRICS_WRITER_URL, PROGRESS_READER_URL, PROGRESS_WRITER_URL, REQUEST_TIMEOUT;

    function AppData() {}

    GENRES = ["black", "death", "doom", "thrash"];

    DEBUG_MODE = false;

    REQUEST_TIMEOUT = 750;

    LYRICS_WRITER_URL = "php/lyrics_writer.php";

    PROGRESS_WRITER_URL = "php/progress_writer.php";

    PROGRESS_READER_URL = "php/progress_reader.php";

    FILTERED_ARTISTS_WRITER_URL = "php/filtered_genre_artist_writer.php";

    LAST_GENRE = "";

    LAST_ARTIST = "";

    LOGGING_ON = false;

    FILTER_ARTISTS = true;

    AppData.getAvailableGenres = function() {
      return GENRES;
    };

    AppData.isDebugMode = function() {
      return DEBUG_MODE;
    };

    AppData.getRequestTimeot = function() {
      return REQUEST_TIMEOUT;
    };

    AppData.getLyricsWriterUrl = function() {
      return LYRICS_WRITER_URL;
    };

    AppData.getProgressWriterUrl = function() {
      return PROGRESS_WRITER_URL;
    };

    AppData.getProgressReaderUrl = function() {
      return PROGRESS_READER_URL;
    };

    AppData.setLastGenre = function(genre) {
      return LAST_GENRE = genre;
    };

    AppData.getLastGenre = function() {
      return LAST_GENRE;
    };

    AppData.setLastArtist = function(artist) {
      return LAST_ARTIST = artist;
    };

    AppData.getLastArtist = function() {
      return LAST_ARTIST;
    };

    AppData.isLoggingOn = function() {
      return LOGGING_ON;
    };

    AppData.doFilterArtists = function() {
      return FILTER_ARTISTS;
    };

    AppData.getFilteredGenreArtistsWriterUrl = function() {
      return FILTERED_ARTISTS_WRITER_URL;
    };

    return AppData;

  })();

}).call(this);
