// Generated by CoffeeScript 1.12.6
(function() {
  this.AppUtils = (function() {
    function AppUtils() {}

    AppUtils.isEmptyData = function(data) {
      return (!data) || (data === void 0) || (data === "") || (data.length === 0);
    };

    return AppUtils;

  })();

}).call(this);
