// Generated by CoffeeScript 1.12.6
(function() {
  this.GenreArtistsReader = (function() {
    function GenreArtistsReader(parentContext1, callbackFunction1, readAllArtists1) {
      this.parentContext = parentContext1;
      this.callbackFunction = callbackFunction1;
      this.readAllArtists = readAllArtists1;
      console.log("Hello from the reader side, readAllArtists = " + this.readAllArtists + " \n\n");
      this.genres = AppData.getAvailableGenres();
      this.genresData = {};
      this.currentGenreIndex = 0;
      this.currentGenre = this.genres[this.currentGenreIndex];
      this.singleGenreArtistsReader = new SingleGenreArtistsReader(this.currentGenre, this.readAllArtists, this);
      this.singleGenreArtistsReader.read();
    }

    GenreArtistsReader.prototype.genreReadingDone = function(genre, data) {
      console.log("Done reading genre " + genre + " \n\n");
      this.genresData[genre] = data;
      if (this.currentGenreIndex === this.genres.length - 1) {
        console.log("\n Finished reading all genres");
        this.callbackFunction.call(this.parentContext, this.genresData);
        return;
      }
      this.currentGenre = this.genres[++this.currentGenreIndex];
      this.singleGenreArtistsReader = new SingleGenreArtistsReader(this.currentGenre, this.readAllArtists, this);
      return this.singleGenreArtistsReader.read();
    };

    GenreArtistsReader.read = function(parentContext, callbackFunction, readAllArtists) {
      return this.genreArtistsReader = new GenreArtistsReader(parentContext, callbackFunction, readAllArtists);
    };

    return GenreArtistsReader;

  })();

  $(function() {
    return console.log("@GenreArtistsReader loaded");
  });

}).call(this);
