// Generated by CoffeeScript 1.12.6
(function() {
  this.SingleGenreArtistsReader = (function() {
    var GENRE_ARTIST_READER_SCRIPT_URL;

    GENRE_ARTIST_READER_SCRIPT_URL = "php/genre_artist_reader.php";

    function SingleGenreArtistsReader(genre, readAllArtists, parentContext) {
      this.genre = genre;
      this.readAllArtists = readAllArtists;
      this.parentContext = parentContext;
      console.log("Started reader for genre " + this.genre + ", readAllArtists = ", this.readAllArtists);
    }

    SingleGenreArtistsReader.prototype.read = function() {
      var data, onTheFlyData;
      data = "genre=" + this.genre + "&readAll=" + this.readAllArtists;
      onTheFlyData = {
        genre: this.genre
      };
      return AjaxUtils.sendAjax('GET', GENRE_ARTIST_READER_SCRIPT_URL, this, this._genreReadingSuccess, this._genreReadingError, data, onTheFlyData);
    };

    SingleGenreArtistsReader.prototype._genreReadingSuccess = function(data, onTheFlyData) {
      data = JSON.parse(data);
      return this.parentContext.genreReadingDone(onTheFlyData.genre, data);
    };

    SingleGenreArtistsReader.prototype._genreReadingError = function(xhr, status) {
      console.log("Error while reading genre data");
      console.log(xhr);
      return console.log(status);
    };

    return SingleGenreArtistsReader;

  })();

  $(function() {
    return console.log("@SingleGenreArtistsReader loaded");
  });

}).call(this);
